// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6oib1E8CgBLZw-TMSF45p3j3zrt4dBw',
    appId: '1:1408986890:web:fe8af8e6dbd4a1f9af94f3',
    messagingSenderId: '1408986890',
    projectId: 'squip-app',
    authDomain: 'squip-app.firebaseapp.com',
    storageBucket: 'squip-app.appspot.com',
    measurementId: 'G-8J998K0L3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmRh0B4tUhBbxwYS8KgWSl14CoEXcYP_I',
    appId: '1:1408986890:android:d1960e142c79a69eaf94f3',
    messagingSenderId: '1408986890',
    projectId: 'squip-app',
    storageBucket: 'squip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmt_YDx5roOG4v08knHySyDVGjzme3brs',
    appId: '1:1408986890:ios:cc52d736b78aa27faf94f3',
    messagingSenderId: '1408986890',
    projectId: 'squip-app',
    storageBucket: 'squip-app.appspot.com',
    iosClientId: '1408986890-1khi9lr61vav8pjoag73r5hhh1bqkvbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.squipProject',
  );
}
